// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./02-names')
const sayHi = require('./02-utils')
const data = require('./02-alternative-flavor')
require('./02-mind-grenade')
console.log(data)
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)
